  export const countries = [
    { "id" :"AD" , "description" : "Andorra"},
    { "id" :"AE" , "description" : "Emiratos Árabes Unidos"},
    { "id" :"AF" , "description" : "Afganistán"},
    { "id" :"AG" , "description" : "Antigua y Barbuda"},
    { "id" :"AI" , "description" : "Anguila"},
    { "id" :"AL" , "description" : "Albania"},
    { "id" :"AM" , "description" : "Armenia"},
    { "id" :"AO" , "description" : "Angola"},
    { "id" :"AQ" , "description" : "Antártida"},
    { "id" :"AR" , "description" : "Argentina"},
    { "id" :"AS" , "description" : "Samoa Americana"},
    { "id" :"AT" , "description" : "Austria"},
    { "id" :"AU" , "description" : "Australia"},
    { "id" :"AW" , "description" : "Aruba"},
    { "id" :"AX" , "description" : "Islas Aland"},
    { "id" :"AZ" , "description" : "Azerbaiyán"},
    { "id" :"BA" , "description" : "Bosnia y Herzegovina"},
    { "id" :"BB" , "description" : "Barbados"},
    { "id" :"BD" , "description" : "Bangladesh"},
    { "id" :"BE" , "description" : "Bélgica"},
    { "id" :"BF" , "description" : "Burkina Faso"},
    { "id" :"BG" , "description" : "Bulgaria"},
    { "id" :"BH" , "description" : "Bahrain"},
    { "id" :"BI" , "description" : "Burundi"},
    { "id" :"BJ" , "description" : "Benin"},
    { "id" :"BL" , "description" : "Santa Barthélemy"},
    { "id" :"BM" , "description" : "islas Bermudas"},
    { "id" :"BN" , "description" : "Brunei Darussalam"},
    { "id" :"BO" , "description" : "Bolivia"},
    { "id" :"BQ" , "description" : "Bonaire Sint Eustatius Saba"},
    { "id" :"BR" , "description" : "Brasil"},
    { "id" :"BS" , "description" : "Bahamas"},
    { "id" :"BT" , "description" : "Bután"},
    { "id" :"BV" , "description" : "Isla bouvet"},
    { "id" :"BW" , "description" : "Botswana"},
    { "id" :"BY" , "description" : "Bielorrusia"},
    { "id" :"BZ" , "description" : "Belice"},
    { "id" :"CA" , "description" : "Canadá"},
    { "id" :"CC" , "description" : "Islas Cocos"},
    { "id" :"CD" , "description" : "Congo"},
    { "id" :"CF" , "description" : "República Centroafricana"},
    { "id" :"CG" , "description" : "el Congo"},
    { "id" :"CH" , "description" : "Suiza"},
    { "id" :"CI" , "description" : "Costa de marfil"},
    { "id" :"CK" , "description" : "Islas Cook"},
    { "id" :"CL" , "description" : "Chile"},
    { "id" :"CM" , "description" : "Camerún"},
    { "id" :"CN" , "description" : "Porcelana"},
    { "id" :"CO" , "description" : "Colombia"},
    { "id" :"CR" , "description" : "Costa Rica"},
    { "id" :"CU" , "description" : "Cuba"},
    { "id" :"CV" , "description" : "Cabo Verde"},
    { "id" :"CW" , "description" : "Curaçao"},
    { "id" :"CX" , "description" : "Isla de Navidad"},
    { "id" :"CY" , "description" : "Chipre"},
    { "id" :"CZ" , "description" : "Chequia"},
    { "id" :"DE" , "description" : "Alemania"},
    { "id" :"DJ" , "description" : "Djibouti"},
    { "id" :"DK" , "description" : "Dinamarca"},
    { "id" :"DM" , "description" : "Dominica"},
    { "id" :"DO" , "description" : "República Dominicana"},
    { "id" :"DZ" , "description" : "Argelia"},
    { "id" :"EC" , "description" : "Ecuador"},
    { "id" :"EE" , "description" : "Estonia"},
    { "id" :"EG" , "description" : "Egipto"},
    { "id" :"EH" , "description" : "Sahara Occidental"},
    { "id" :"ER" , "description" : "Eritrea"},
    { "id" :"ES" , "description" : "España"},
    { "id" :"ET" , "description" : "Etiopía"},
    { "id" :"FI" , "description" : "Finlandia"},
    { "id" :"FJ" , "description" : "Fiji"},
    { "id" :"FK" , "description" : "Islas Malvinas"},
    { "id" :"FM" , "description" : "Micronesia"},
    { "id" :"FO" , "description" : "Islas Faroe"},
    { "id" :"FR" , "description" : "Francia"},
    { "id" :"GA" , "description" : "Gabón"},
    { "id" :"GB" , "description" : "Reino Unido de Gran Bretaña e Irlanda del Norte"},
    { "id" :"GD" , "description" : "Granada"},
    { "id" :"GE" , "description" : "Georgia"},
    { "id" :"GF" , "description" : "Guayana Francesa"},
    { "id" :"GG" , "description" : "Guernsey"},
    { "id" :"GH" , "description" : "Ghana"},
    { "id" :"GI" , "description" : "Gibraltar"},
    { "id" :"GL" , "description" : "Groenlandia"},
    { "id" :"GM" , "description" : "Gambia (el)"},
    { "id" :"GN" , "description" : "Guinea"},
    { "id" :"GP" , "description" : "Guadeloupo"},
    { "id" :"GQ" , "description" : "Guinea Ecuatorial"},
    { "id" :"GR" , "description" : "Grecia"},
    { "id" :"GS" , "description" : "Georgia del sur y las islas Sandwich del sur"},
    { "id" :"GT" , "description" : "Guatemala"},
    { "id" :"GU" , "description" : "Guam"},
    { "id" :"GW" , "description" : "Guinea-Bissau"},
    { "id" :"GY" , "description" : "Guayana"},
    { "id" :"HK" , "description" : "Hong Kong"},
    { "id" :"HM" , "description" : "Escuché Island y Islas McDonald"},
    { "id" :"HN" , "description" : "Honduras"},
    { "id" :"HR" , "description" : "Croacia"},
    { "id" :"HT" , "description" : "Haití"},
    { "id" :"HU" , "description" : "Hungría"},
    { "id" :"ID" , "description" : "Indonesia"},
    { "id" :"IE" , "description" : "Irlanda"},
    { "id" :"IL" , "description" : "Israel"},
    { "id" :"IM" , "description" : "Isla del hombre"},
    { "id" :"IN" , "description" : "India"},
    { "id" :"IO" , "description" : "Territorio Británico del Océano Índico"},
    { "id" :"IQ" , "description" : "Irak"},
    { "id" :"IR" , "description" : "Irán"},
    { "id" :"IS" , "description" : "Islandia"},
    { "id" :"IT" , "description" : "Italia"},
    { "id" :"JE" , "description" : "Jersey"},
    { "id" :"JM" , "description" : "Jamaica"},
    { "id" :"JO" , "description" : "Jordán"},
    { "id" :"JP" , "description" : "Japón"},
    { "id" :"KE" , "description" : "Kenia"},
    { "id" :"KG" , "description" : "Kirguistán"},
    { "id" :"KH" , "description" : "Camboya"},
    { "id" :"KI" , "description" : "Kiribati"},
    { "id" :"KM" , "description" : "Comoras"},
    { "id" :"KN" , "description" : "Saint Kitts y Nevis"},
    { "id" :"KP" , "description" : "Corea del Norte"},
    { "id" :"KR" , "description" : "Corea del Sur"},
    { "id" :"KW" , "description" : "Kuwait"},
    { "id" :"KY" , "description" : "Islas Caimán"},
    { "id" :"KZ" , "description" : "Kazajstán"},
    { "id" :"LA" , "description" : "República Democrática Popular de Lao"},
    { "id" :"LB" , "description" : "Líbano"},
    { "id" :"LC" , "description" : "Santa Lucía"},
    { "id" :"LI" , "description" : "Liechtenstein"},
    { "id" :"LK" , "description" : "Sri Lanka"},
    { "id" :"LR" , "description" : "Liberia"},
    { "id" :"LS" , "description" : "Lesoto"},
    { "id" :"LT" , "description" : "Lituania"},
    { "id" :"LU" , "description" : "Luxemburgo"},
    { "id" :"LV" , "description" : "Letonia"},
    { "id" :"LY" , "description" : "Libia"},
    { "id" :"MA" , "description" : "Marruecos"},
    { "id" :"MC" , "description" : "Mónaco"},
    { "id" :"MD" , "description" : "Moldava"},
    { "id" :"ME" , "description" : "Montenegro"},
    { "id" :"MF" , "description" : "San Martín"},
    { "id" :"MG" , "description" : "Madagascar"},
    { "id" :"MH" , "description" : "Islas Marshall"},
    { "id" :"MK" , "description" : "Macedonia del Norte"},
    { "id" :"ML" , "description" : "Malí"},
    { "id" :"MM" , "description" : "Myanmar"},
    { "id" :"MN" , "description" : "Mongolia"},
    { "id" :"MO" , "description" : "Macao"},
    { "id" :"MP" , "description" : "Islas Marianas del Norte"},
    { "id" :"MQ" , "description" : "Martinica"},
    { "id" :"MR" , "description" : "Mauritania"},
    { "id" :"MS" , "description" : "Montserrat"},
    { "id" :"MT" , "description" : "Malta"},
    { "id" :"MU" , "description" : "Mauricio"},
    { "id" :"MV" , "description" : "Maldivas"},
    { "id" :"MW" , "description" : "Malawi"},
    { "id" :"MX" , "description" : "México"},
    { "id" :"MY" , "description" : "Malasia"},
    { "id" :"MZ" , "description" : "Mozambique"},
    { "id" :"NA" , "description" : "Namibia"},
    { "id" :"NC" , "description" : "Nueva Caledonia"},
    { "id" :"NE" , "description" : "Níger"},
    { "id" :"NF" , "description" : "Isla Norfolk"},
    { "id" :"NG" , "description" : "Nigeria"},
    { "id" :"NI" , "description" : "Nicaragua"},
    { "id" :"NL" , "description" : "Países Bajos"},
    { "id" :"NO" , "description" : "Noruega"},
    { "id" :"NP" , "description" : "Nepal"},
    { "id" :"NR" , "description" : "Nauru"},
    { "id" :"NU" , "description" : "Niue"},
    { "id" :"NZ" , "description" : "Nueva Zelanda"},
    { "id" :"OM" , "description" : "Omán"},
    { "id" :"PA" , "description" : "Panamá"},
    { "id" :"PE" , "description" : "Perú"},
    { "id" :"PF" , "description" : "Polinesia francés"},
    { "id" :"PG" , "description" : "Papúa Nueva Guinea"},
    { "id" :"PH" , "description" : "Filipinas"},
    { "id" :"PK" , "description" : "Pakistán"},
    { "id" :"PL" , "description" : "Polonia"},
    { "id" :"PM" , "description" : "Saint Pierre y Miquelon"},
    { "id" :"PN" , "description" : "Pitcairn"},
    { "id" :"PR" , "description" : "Puerto Rico"},
    { "id" :"PS" , "description" : "Palestina, estado de"},
    { "id" :"PT" , "description" : "Portugal"},
    { "id" :"PW" , "description" : "Palau"},
    { "id" :"PY" , "description" : "Paraguay"},
    { "id" :"QA" , "description" : "Katar"},
    { "id" :"RE" , "description" : "Reunión"},
    { "id" :"RO" , "description" : "Rumania"},
    { "id" :"RS" , "description" : "Serbia"},
    { "id" :"RU" , "description" : "Federación Rusa"},
    { "id" :"RW" , "description" : "Ruanda"},
    { "id" :"SA" , "description" : "Arabia Saudita"},
    { "id" :"SB" , "description" : "Islas Salomón"},
    { "id" :"SC" , "description" : "Seychelles"},
    { "id" :"SD" , "description" : "Sudán"},
    { "id" :"SE" , "description" : "Suecia"},
    { "id" :"SG" , "description" : "Singapur"},
    { "id" :"SI" , "description" : "Eslovenia"},
    { "id" :"SK" , "description" : "Eslovaquia"},
    { "id" :"SL" , "description" : "Sierra Leona"},
    { "id" :"SM" , "description" : "San Marino"},
    { "id" :"SN" , "description" : "Senegal"},
    { "id" :"SO" , "description" : "Somalia"},
    { "id" :"SR" , "description" : "Surinam"},
    { "id" :"SS" , "description" : "Sudán del Sur"},
    { "id" :"ST" , "description" : "Santo Tomé y Príncipe"},
    { "id" :"SV" , "description" : "El Salvador"},
    { "id" :"SX" , "description" : "Sint Maarten"},
    { "id" :"SY" , "description" : "República Árabe Siria"},
    { "id" :"SZ" , "description" : "Eswatini"},
    { "id" :"TC" , "description" : "Islas Turcas y Caicos"},
    { "id" :"TD" , "description" : "Chad"},
    { "id" :"TF" , "description" : "Territorios Franceses del Sur"},
    { "id" :"TG" , "description" : "Togo"},
    { "id" :"TH" , "description" : "Tailandia"},
    { "id" :"TJ" , "description" : "Tayikistán"},
    { "id" :"TK" , "description" : "Tokelau"},
    { "id" :"TL" , "description" : "Timor-Leste"},
    { "id" :"TM" , "description" : "Turkmenistán"},
    { "id" :"TN" , "description" : "Túnez"},
    { "id" :"TO" , "description" : "Tonga"},
    { "id" :"TR" , "description" : "Pavo"},
    { "id" :"TT" , "description" : "Trinidad y Tobago"},
    { "id" :"TV" , "description" : "Tuvalu"},
    { "id" :"TW" , "description" : "Taiwán"},
    { "id" :"TZ" , "description" : "Tanzania"},
    { "id" :"UA" , "description" : "Ucrania"},
    { "id" :"UG" , "description" : "Uganda"},
    { "id" :"UM" , "description" : "Islas menores de los Estados Unidos."},
    { "id" :"US" , "description" : "Estados Unidos de América"},
    { "id" :"UY" , "description" : "Uruguay"},
    { "id" :"UZ" , "description" : "Uzbekistán"},
    { "id" :"VA" , "description" : "Santa Sede"},
    { "id" :"VC" , "description" : "San Vicente y las Granadinas"},
    { "id" :"VE" , "description" : "Venezuela"},
    { "id" :"VG" , "description" : "Islas Virgenes"},
    { "id" :"VI" , "description" : "Islas Virgenes"},
    { "id" :"VN" , "description" : "Vietnam"},
    { "id" :"VU" , "description" : "Vanuatu"},
    { "id" :"WF" , "description" : "Wallis y Futuna"},
    { "id" :"WS" , "description" : "Samoa"},
    { "id" :"YE" , "description" : "Yemen"},
    { "id" :"YT" , "description" : "Mayotte"},
    { "id" :"ZA" , "description" : "Sudáfrica"},
    { "id" :"ZM" , "description" : "Zambia"},
    { "id" :"ZW" , "description" : "Zimbabue"}
]